// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class carUpgraded extends ethereum.Event {
  get params(): carUpgraded__Params {
    return new carUpgraded__Params(this);
  }
}

export class carUpgraded__Params {
  _event: carUpgraded;

  constructor(event: carUpgraded) {
    this._event = event;
  }

  get Contract(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get Upgradation(): string {
    return this._event.parameters[1].value.toString();
  }
}

export class Car extends ethereum.SmartContract {
  static bind(address: Address): Car {
    return new Car("Car", address);
  }

  getCarOwner(): Address {
    let result = super.call("getCarOwner", "getCarOwner():(address)", []);

    return result[0].toAddress();
  }

  try_getCarOwner(): ethereum.CallResult<Address> {
    let result = super.tryCall("getCarOwner", "getCarOwner():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getCarSpecs(): string {
    let result = super.call("getCarSpecs", "getCarSpecs():(string)", []);

    return result[0].toString();
  }

  try_getCarSpecs(): ethereum.CallResult<string> {
    let result = super.tryCall("getCarSpecs", "getCarSpecs():(string)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get NewCarOwner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get NewSpecs(): string {
    return this._call.inputValues[1].value.toString();
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class CarUpgradationCall extends ethereum.Call {
  get inputs(): CarUpgradationCall__Inputs {
    return new CarUpgradationCall__Inputs(this);
  }

  get outputs(): CarUpgradationCall__Outputs {
    return new CarUpgradationCall__Outputs(this);
  }
}

export class CarUpgradationCall__Inputs {
  _call: CarUpgradationCall;

  constructor(call: CarUpgradationCall) {
    this._call = call;
  }

  get Caller(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get Upgrade(): string {
    return this._call.inputValues[1].value.toString();
  }
}

export class CarUpgradationCall__Outputs {
  _call: CarUpgradationCall;

  constructor(call: CarUpgradationCall) {
    this._call = call;
  }
}
